name : CI/CD Pipline

on:
  push:
    branches: 
        -main

  pull_request:
     branches:
         -main

jobs:
  build:
   runs-on: ubuntu-latest


  steps:
    - name : Checkout code
      uses: actions/checkout@v3
   
    - name : Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version : 16 
    
    - name : Install dependencies
      run : npm install

    - name : Build Docker image
      run :
        docker build -t learning .
      
  deploy: 
    needs : build
    runs-on: ubuntu-latest

  steps:
    - name: Deploy (placeholder for manual deployment)
      run: echo 'Deploy to production' >> deploy.log

